server:
  port: 8012

spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      url: mongodb://127.0.0.1:27017
      database: springbootwebapp

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka